services:
  - type: web
    name: aadhar-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web:app --workers 1 --threads 4
    envVars:
      - key: BOT_TOKEN
        sync: false
