services:
  - type: web
    name: aadhar-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: BOT_TOKEN
        sync: false
